services:
  - type: web
    name: whanau-tech-backend
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:app
    healthCheckPath: /api/hello
    autoDeploy: true

  - type: static
    name: whanau-tech-frontend
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/build
    autoDeploy: true
